[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pyright]
include = ["src",
    "app",
    "tux"
]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
include = ["."]
typeCheckingMode = "strict"

# strict disabled checks
reportUnknownParameterType = false
reportMissingParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeStubs = false

pythonVersion = "3.11"
pythonPlatform = "all"
