# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      # Install pyenv and Python 3.11
      - name: 'Set up Python 3.11 and pyenv'
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential libssl-dev zlib1g-dev \
                                  libbz2-dev libreadline-dev libsqlite3-dev wget \
                                  curl llvm libncurses5-dev libncursesw5-dev \
                                  xz-utils tk-dev libffi-dev liblzma-dev \
                                  python3-openssl git

          curl https://pyenv.run | bash
          echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> $HOME/.bashrc
          echo 'eval "$(pyenv init --path)"' >> $HOME/.bashrc
          echo 'eval "$(pyenv virtualenv-init -)"' >> $HOME/.bashrc
          exec "$SHELL"

          pyenv install 3.11.0
          pyenv global 3.11.0

          # Ensure the changes to PATH are available in the current shell
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv virtualenv-init -)"

      # Install Poetry
      - name: 'Install Poetry'
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Run Poetry commands
      - name: 'Run Poetry Update'
        run: |
          poetry --version
          poetry update
