name: 'Linting'
on: [ push, pull_request ]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install Poetry
      - name: Poetry Install
        uses: snok/install-poetry@v1.3.4

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      # Use Ruff Action for linting
      - name: Run Ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 'latest' # Use the latest version of Ruff
          args: '--check .' # Replace with any arguments you want to pass to Ruff

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style fixes by ruff'
