name: 'OpenCommit Action'

on:
  push:
    branches-ignore: [main, master, dev, development, release]
    # Trigger the workflow only for the initial push to any branch
    # subsequent pushes created from this workflow will be ignored
    paths-ignore:
      - 'opencommit/**'

jobs:
  opencommit:
    if: ${{ github.event_name == 'push' && github.ref != 'refs/heads/opencommit' }}
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.ADMIN_PAT || github.token }}
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT || github.token }}

        env:
          OCO_OPENAI_API_KEY: ${{ secrets.OCO_OPENAI_API_KEY }}
          OCO_TOKENS_MAX_INPUT: 4096
          OCO_TOKENS_MAX_OUTPUT: 500
          OCO_OPENAI_BASE_PATH: ''
          OCO_DESCRIPTION: false
          OCO_EMOJI: false
          OCO_MODEL: gpt-4
          OCO_LANGUAGE: en
          OCO_PROMPT_MODULE: conventional-commit
